### ISSUE TITLE
Are you able to use Flow Router with this instead of React Router?

### ISSUE THREAD

**Issue by DanGamble89** [thereactivestack/meteor-webpack-react-kickstart#7]
Could i include Components from the React folder in the Meteor folder at all? Or would it be a case of using the global created by Meteor in the React folder?

**Comment by eXon** [comment]
If you want to use FlowRouter with this project. you can add it to the Meteor project and use FlowRouter within react/index.js. The reason React components are out of the Meteor folder is to make sure it doesn't restart. Webpack is taking care of updating the client with no page refresh.

**Comment by DanGamble89** [comment]
Awesome thank you! Yea I understand the divide it makes sense. The hot
reload is much nicer than the restarts. Thanks for the project. It's a
really nice way to get started with Meteor and React, looking forward to
it's evolution :)

**Comment by andreasbhansen** [comment]
Did you get this to work, @DanGamble89? I'm trying to do the same, but when using FlowRouter in the react/index.jsx (I also tried with an index.js) file, I only get a browser console error, ```There is no route for the path: /```

**Comment by DanGamble89** [comment]
@andreasbhansen That's the exact same problem I experienced regardless of what I tried to fix it. I tried it inside the Meteor folder as well as the React folder. If you do manage to get it working, please let me know :)

**Comment by andreasbhansen** [comment]
I will, @DanGamble89  :) 
Have you tried to do switch to FlowRouter, @eXon ?

**Comment by andreasbhansen** [comment]
OK, quick update @DanGamble89. I now added another file, ```/meteor/app.js``` and pasted  ```FlowRouter.wait();``` into it. Then, in the ```react/index.jsx``` file, I have my routes, and ```FlowRouter.initialize();``` below. So that seems to work. 

However, I think I'm having some problems with Material Design Lite with FlowRouter that I didn't have with react-router. Buttons not working and input placeholders not being removed. Have to check more into that.

**Comment by DanGamble89** [comment]
Awesome @andreasbhansen. I've never used Flow Router before so didn't have much of an idea of what to do. I'll give this a try today and see how that goes, thanks!

**Comment by andreasbhansen** [comment]
Good luck, @DanGamble89.

If anyone sees this and wonders how to fix FlowRouter + MDL: https://github.com/Zodiase/meteor-mdl

**Comment by DanGamble89** [comment]
@andreasbhansen 

Just tried it following your instructions and it worked a charm :D I'll just write them out a bit more verbose just incase anyone as inexperienced as me struggles as well:

This is on OSX:

* `git clone git@github.com:thereactivestack/kickstart.git`
* `cd kickstart`
* `npm i`
* `./scripts/run-dev.sh`
* Run these commands:
```bash
./meteor.sh add kadira:flow-router
./meteor.sh add kadira:react-layout
./meteor.sh remove reactrouter:react-router-ssr
```
* Create this file: `echo 'FlowRouter.wait();' > meteor/app.js`
* Open `react/index.jsx` in your editor of choice then:

```javascript
import App from './App';
import TodoApp from './todo/TodoApp';

FlowRouter.route('/', {
  action(params, queryParams) {
    ReactLayout.render(TodoApp);
  },
});
        
FlowRouter.initialize();
```

And voila!

@eXon Might be worth adding this to the `README.md` or a wiki of some kind :)

**Comment by andreasbhansen** [comment]
That's good to know! 
Great instructions :+1:

**Comment by eXon** [comment]
I will add a branch for FlowRouter. However, a lot of great features like SSR and code splitting will not be there.

**Comment by DanGamble89** [comment]
What exactly is 'Code Splitting'? @eXon

**Comment by DanGamble89** [comment]
@eXon nevermind, just re-read your updated README :)

**Comment by andreasbhansen** [comment]
Oh, did not think about the code splitting – that could be a dealbreaker for Flow Router... Flow Router supports SSR afaik, but that might require some extra configuration with Webpack?

**Comment by txs** [comment]
So how do I cofig to make flow router ssr work with webpack
